### ISSUE TITLE
1.19.2 Forge - Mushroom_pond mixin problem

### ISSUE THREAD

**Issue by NovaXCIV** [FinnSetchell/MoogsVanillaStructuresV2#26]
```
[12:17:16] [Worker-Main-1/ERROR] [minecraft/StructureTemplateManager]: Couldn't load structure mvs:nature/mushroom_pond/mushroom_pond_upper
net.minecraft.ReportedException: Loading NBT data
        at net.minecraft.nbt.CompoundTag.m_128413_(CompoundTag.java:466) ~[server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:pehkui.mixins.json:compat116plus.NbtCompoundMixin,pl:mixin:A}
        at net.minecraft.nbt.CompoundTag$1.m_7300_(CompoundTag.java:43) ~[server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:classloading}
        at net.minecraft.nbt.CompoundTag$1.m_7300_(CompoundTag.java:30) ~[server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:classloading}
        at net.minecraft.nbt.ListTag$1.m_7300_(ListTag.java:43) ~[server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:classloading}
        at net.minecraft.nbt.ListTag$1.m_7300_(ListTag.java:26) ~[server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:classloading}
        at net.minecraft.nbt.CompoundTag.m_128413_(CompoundTag.java:460) ~[server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:pehkui.mixins.json:compat116plus.NbtCompoundMixin,pl:mixin:A}
        at net.minecraft.nbt.CompoundTag$1.m_7300_(CompoundTag.java:43) ~[server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:classloading}
        at net.minecraft.nbt.CompoundTag$1.m_7300_(CompoundTag.java:30) ~[server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:classloading}
        at net.minecraft.nbt.NbtIo.m_128930_(NbtIo.java:279) ~[server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:classloading,re:mixin}
        at net.minecraft.nbt.NbtIo.m_128934_(NbtIo.java:225) ~[server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:classloading,re:mixin}
        at net.minecraft.nbt.NbtIo.m_128939_(NbtIo.java:52) ~[server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:classloading,re:mixin}
        at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230377_(StructureTemplateManager.java:222) ~[server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:mixin,re:classloading,pl:mixin:APP:mvs-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:A}
        at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230372_(StructureTemplateManager.java:212) ~[server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:mixin,re:classloading,pl:mixin:APP:mvs-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:A}
        at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230427_(StructureTemplateManager.java:124) ~[server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:mixin,re:classloading,pl:mixin:APP:mvs-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:A}
        at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230425_(StructureTemplateManager.java:102) ~[server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:mixin,re:classloading,pl:mixin:APP:mvs-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:A}
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740) ~[?:?] {re:mixin}
        at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230407_(StructureTemplateManager.java:92) ~[server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:mixin,re:classloading,pl:mixin:APP:mvs-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:A}
        at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplateManager.m_230359_(StructureTemplateManager.java:80) ~[server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:mixin,re:classloading,pl:mixin:APP:mvs-common.mixins.json:structures.StructureTemplateManagerAccessor,pl:mixin:A}
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar%2375!/:?] {}
        at net.minecraft.world.level.levelgen.structure.pools.SinglePoolElement.m_227299_(SinglePoolElement.java:85) ~[server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:yungsapi.mixins.json:accessor.SinglePoolElementAccessor,pl:mixin:APP:mvs-common.mixins.json:structures.SinglePoolElementAccessor,pl:mixin:A}
        at net.minecraft.world.level.levelgen.structure.pools.SinglePoolElement.m_214015_(SinglePoolElement.java:118) ~[server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:yungsapi.mixins.json:accessor.SinglePoolElementAccessor,pl:mixin:APP:mvs-common.mixins.json:structures.SinglePoolElementAccessor,pl:mixin:A}
        at com.finndog.mvs.world.structures.pieces.PieceLimitedJigsawManager.assembleJigsawStructure(PieceLimitedJigsawManager.java:89) ~[mvs-4.1.1-1.19.2-forge.jar%23564!/:?] {re:classloading}
        at com.finndog.mvs.world.structures.GenericJigsawStructure.m_214086_(GenericJigsawStructure.java:207) ~[mvs-4.1.1-1.19.2-forge.jar%23564!/:?] {re:classloading}
        at net.minecraft.world.level.levelgen.structure.Structure.m_226596_(Structure.java:84) ~[server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:mixin,xf:fml:forge:structure,re:classloading,xf:fml:forge:structure,pl:mixin:APP:structure_gel.mixins.json:StructureMixin,pl:mixin:A}
        at net.minecraft.world.level.chunk.ChunkGenerator.m_223104_(ChunkGenerator.java:638) ~[server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:disablestructures.mixins.json:MixinChunkGenerator,pl:mixin:APP:betterjungletemples.mixins.json:DisableVanillaJungleTempleMixin,pl:mixin:APP:citadel.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:betteroceanmonuments.mixins.json:DisableVanillaMonumentsMixin,pl:mixin:APP:betterdeserttemples.mixins.json:DisableVanillaPyramidsMixin,pl:mixin:A}
        at net.minecraft.world.level.chunk.ChunkGenerator.m_223066_(ChunkGenerator.java:591) ~[server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:disablestructures.mixins.json:MixinChunkGenerator,pl:mixin:APP:betterjungletemples.mixins.json:DisableVanillaJungleTempleMixin,pl:mixin:APP:citadel.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:betteroceanmonuments.mixins.json:DisableVanillaMonumentsMixin,pl:mixin:APP:betterdeserttemples.mixins.json:DisableVanillaPyramidsMixin,pl:mixin:A}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}
        at java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720) ~[?:?] {}
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
        at net.minecraft.world.level.chunk.ChunkGenerator.m_223164_(ChunkGenerator.java:573) ~[server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:disablestructures.mixins.json:MixinChunkGenerator,pl:mixin:APP:betterjungletemples.mixins.json:DisableVanillaJungleTempleMixin,pl:mixin:APP:citadel.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:betteroceanmonuments.mixins.json:DisableVanillaMonumentsMixin,pl:mixin:APP:betterdeserttemples.mixins.json:DisableVanillaPyramidsMixin,pl:mixin:A}
        at net.minecraft.world.level.chunk.ChunkStatus.m_223360_(ChunkStatus.java:59) ~[server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.world.level.chunk.ChunkStatus.m_223279_(ChunkStatus.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$25(ChunkMap.java:621) ~[server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:pehkui.mixins.json:compat116plus.compat1201minus.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:emotecraft.mixins.json:ChunkMapAccessor,pl:mixin:APP:smoothchunk.mixins.json:ChunkMapMixin,pl:mixin:APP:canary.mixins.json:world.player_chunk_tick.ChunkMapMixin,pl:mixin:APP:debugify-common.mixins.json:basic.server.mc224729.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:smallships-common-soft.mixins.json:leashing.ChunkMapMixin,pl:mixin:A}
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar%2375!/:?] {}
        at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$27(ChunkMap.java:619) ~[server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:pehkui.mixins.json:compat116plus.compat1201minus.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:emotecraft.mixins.json:ChunkMapAccessor,pl:mixin:APP:smoothchunk.mixins.json:ChunkMapMixin,pl:mixin:APP:canary.mixins.json:world.player_chunk_tick.ChunkMapMixin,pl:mixin:APP:debugify-common.mixins.json:basic.server.mc224729.ThreadedAnvilChunkStorageMixin,pl:mixin:APP:smallships-common-soft.mixins.json:leashing.ChunkMapMixin,pl:mixin:A}
        at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
        at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:classloading}
        at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) [server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:classloading}
        at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) [server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:classloading}
        at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) [server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:classloading}
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) [?:?] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?] {}
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?] {re:computing_frames}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?] {re:computing_frames}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?] {}
Caused by: java.io.IOException: Invalid tag id: 19
        at net.minecraft.nbt.TagType$1.m_197591_(TagType.java:58) ~[server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:classloading}
        at net.minecraft.nbt.TagType$1.m_7300_(TagType.java:63) ~[server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:classloading}
        at net.minecraft.nbt.TagType$1.m_7300_(TagType.java:56) ~[server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:classloading}
        at net.minecraft.nbt.CompoundTag.m_128413_(CompoundTag.java:460) ~[server-1.19.2-20220805.130853-srg.jar%23679!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:pehkui.mixins.json:compat116plus.NbtCompoundMixin,pl:mixin:A}
        ... 52 more
```

**Comment by FinnSetchell** [comment]
Which version are you using? Should be fixed in 4.1.1

**Comment by cl0ck-byte** [comment]
Not exclusive to Forge - also occurs on Fabric 1.19.2 

> Which version are you using? Should be fixed in 4.1.1

It wasn't as I have 4.1.1 (modrinth doesn't have it for some reason) and it still occurs

```
[14:59:50] [Server thread/ERROR]: Couldn't load structure mvs:nature/mushroom_pond/mushroom_pond_upper
net.minecraft.class_148: Loading NBT data
        at net.minecraft.class_2487.method_10581(class_2487.java:495) ~[server-intermediary.jar:?]
        at net.minecraft.class_2487$1.method_23240(class_2487.java:71) ~[server-intermediary.jar:?]
        at net.minecraft.class_2487$1.method_23262(class_2487.java:57) ~[server-intermediary.jar:?]
        at net.minecraft.class_2499$1.method_23249(class_2499.java:43) ~[server-intermediary.jar:?]
        at net.minecraft.class_2499$1.method_23262(class_2499.java:26) ~[server-intermediary.jar:?]
        at net.minecraft.class_2487.method_10581(class_2487.java:489) ~[server-intermediary.jar:?]
        at net.minecraft.class_2487$1.method_23240(class_2487.java:71) ~[server-intermediary.jar:?]
        at net.minecraft.class_2487$1.method_23262(class_2487.java:57) ~[server-intermediary.jar:?]
        at net.minecraft.class_2507.method_10626(class_2507.java:147) ~[server-intermediary.jar:?]
        at net.minecraft.class_2507.method_10625(class_2507.java:91) ~[server-intermediary.jar:?]
        at net.minecraft.class_2507.method_10629(class_2507.java:36) ~[server-intermediary.jar:?]
        at net.minecraft.class_3485.method_15090(class_3485.java:222) ~[server-intermediary.jar:?]
        at net.minecraft.class_3485.method_44231(class_3485.java:212) ~[server-intermediary.jar:?]
        at net.minecraft.class_3485.method_15088(class_3485.java:124) ~[server-intermediary.jar:?]
        at net.minecraft.class_3485.method_44245(class_3485.java:102) ~[server-intermediary.jar:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740) ~[?:?]
        at net.minecraft.class_3485.method_15094(class_3485.java:92) ~[server-intermediary.jar:?]
        at net.minecraft.class_3485.method_15091(class_3485.java:80) ~[server-intermediary.jar:?]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar:?]
        at net.minecraft.class_3781.method_27233(class_3781.java:85) ~[server-intermediary.jar:?]
        at net.minecraft.class_3781.method_16628(class_3781.java:118) ~[server-intermediary.jar:?]
        at net.minecraft.class_3790.<init>(class_3790.java:58) ~[server-intermediary.jar:?]
        at net.minecraft.class_6624.method_38711(class_6624.java:73) ~[server-intermediary.jar:?]
        at net.minecraft.class_3449.method_41621(class_3449.java:66) ~[server-intermediary.jar:?]
        at net.minecraft.class_2852.method_12392(class_2852.java:480) ~[server-intermediary.jar:?]
        at net.minecraft.class_2852.method_12395(class_2852.java:211) ~[server-intermediary.jar:?]
        at net.minecraft.class_3898.method_43375(class_3898.java:625) ~[server-intermediary.jar:?]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
        at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:557) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:566) ~[server-intermediary.jar:?]
        at net.minecraft.class_3215.method_19492(class_3215.java:279) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.io.IOException: Invalid tag id: 19
        at net.minecraft.class_4614$1.method_39878(class_4614.java:58) ~[server-intermediary.jar:?]
        at net.minecraft.class_4614$1.method_23264(class_4614.java:63) ~[server-intermediary.jar:?]
        at net.minecraft.class_4614$1.method_23262(class_4614.java:56) ~[server-intermediary.jar:?]
        at net.minecraft.class_2487.method_10581(class_2487.java:489) ~[server-intermediary.jar:?]
        ... 40 more
```
