### ISSUE TITLE
This structure floods?

### ISSUE THREAD

**Issue by xbxbxb123** [FinnSetchell/MoogsVanillaStructuresV2#49]
This structure has water leaking out for some reason 

![Image](https://github.com/user-attachments/assets/dbe533c8-9985-4275-808c-71f466ff1c07) 

I am not sure what it it called but I am pretty sure it is from this mod because it looks very similar to the desert pump structure

**Comment by FinnSetchell** [comment]
which version are you using? This should be fixed on some newer versions

**Comment by xbxbxb123** [comment]
the newest one on forge 1.20.1

**Comment by creamIcec** [comment]
still exists for a different structure mvs:small_well(used wits mod for name) in newest version 5.0.21-1.20(forge 1.20.1).

<img width="2560" height="1564" alt="Image" src="https://github.com/user-attachments/assets/c98d71d6-7921-4531-b9d7-b33d9917703e" />

<img width="470" height="49" alt="Image" src="https://github.com/user-attachments/assets/dd39be7c-b18d-4dee-a629-23f81cb09854" />

**Comment by TheGoldenWorld** [comment]
Hi, I have fixed the two wells for the 1.20.1. The issue may be the waterlogged feature messing around with the stairs and the trapdoors. Thanks for your feedback!
